import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Overlay from "./components/Overlay";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-peakblue relative antialiased`}>
        
        {/* lift all content above the overlay */}
        <div className="relative z-10">
          <Navbar />
          {children}
          <div className="relative overflow-visible">
            <Overlay />                 {/* will anchor to this wrapper */}
            <div className="relative z-10">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
